import { Job } from "./job-card";

export const mockJobs: (Job & { matchPercentage?: number; featured?: boolean })[] = [
  {
    id: "job-001",
    title: "Senior React Engineer",
    company: { name: "Linear", verified: true },
    location: "San Francisco, CA",
    isRemote: true,
    salary: "$160k - $210k",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    postedAt: "2 hours ago",
    matchPercentage: 98,
    featured: true,
  },
  {
    id: "job-002",
    title: "Staff Frontend Engineer",
    company: { name: "Stripe", verified: true },
    location: "New York, NY",
    isRemote: false,
    salary: "$200k - $250k",
    employmentType: "Full-time",
    experienceLevel: "Staff",
    skills: ["React", "Redux", "System Design", "Performance"],
    postedAt: "5 hours ago",
    matchPercentage: 94,
  },
  {
    id: "job-003",
    title: "Frontend Developer",
    company: { name: "Vercel", verified: true },
    location: "Remote",
    isRemote: true,
    salary: "$130k - $170k",
    employmentType: "Full-time",
    experienceLevel: "Mid-Level",
    skills: ["Next.js", "React", "Tailwind CSS"],
    postedAt: "1 day ago",
    matchPercentage: 88,
  },
  {
    id: "job-004",
    title: "UI/UX Developer",
    company: { name: "Notion", verified: false },
    location: "San Francisco, CA",
    isRemote: true,
    salary: "$140k - $180k",
    employmentType: "Full-time",
    experienceLevel: "Mid-Level",
    skills: ["Figma", "React", "CSS Animation", "Accessibility"],
    postedAt: "2 days ago",
    matchPercentage: 91,
  },
  {
    id: "job-005",
    title: "Lead Web Engineer",
    company: { name: "Supabase", verified: true },
    location: "Remote",
    isRemote: true,
    salary: "$180k - $220k",
    employmentType: "Full-time",
    experienceLevel: "Lead",
    skills: ["React", "TypeScript", "PostgreSQL", "WebSockets"],
    postedAt: "3 days ago",
    matchPercentage: 82,
  },
  {
    id: "job-006",
    title: "React Native Developer",
    company: { name: "Airbnb", verified: true },
    location: "Seattle, WA",
    isRemote: false,
    salary: "$150k - $190k",
    employmentType: "Contract",
    experienceLevel: "Senior",
    skills: ["React Native", "iOS", "Android", "Mobile Design"],
    postedAt: "4 days ago",
    matchPercentage: 75,
  },
  {
    id: "job-007",
    title: "Frontend Architect",
    company: { name: "Netflix", verified: true },
    location: "Los Gatos, CA",
    isRemote: false,
    salary: "$250k - $300k",
    employmentType: "Full-time",
    experienceLevel: "Principal",
    skills: ["React", "Micro-frontends", "Performance", "Video Streaming"],
    postedAt: "1 week ago",
    matchPercentage: 96,
  },
  {
    id: "job-008",
    title: "Full Stack Developer (React focus)",
    company: { name: "Discord", verified: true },
    location: "Remote",
    isRemote: true,
    salary: "$140k - $180k",
    employmentType: "Full-time",
    experienceLevel: "Mid-Level",
    skills: ["React", "Node.js", "WebRTC", "Elixir"],
    postedAt: "1 week ago",
    matchPercentage: 85,
  }
];
